name: Feature request
description: Suggest an improvement or new feature.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature ideas are welcome — especially improvements to guides, troubleshooting coverage, and tools like the config generator.
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the pain point or user story.
      placeholder: "As a user, I want..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should the site/tool do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Extra context
      description: Links, screenshots, references, or examples.
    validations:
      required: false

